// Generated by scripts/build.mjs from src/host.js — do not edit directly.
// dsh-song-search — host half（静态 bundle 形态）
// 业务：
//   1. 在 DSH 的 ctx.web 搜索接缝注册 Exa、Brave、Tavily、Serper 搜索提供商
//   2. 提供 RPC（/_dsh/dsh-song-search/{getSearchConfig,setSearchConfig}），
//      供设置「搜索服务」页读取/修改 profile 的 cordis.patch.yml（搜索商 + 钥匙）
// 原则：
//   1. 零 DSH 内部依赖——不 import 任何 @deepseek-ai 包，只用 Node 内置能力与通用 yaml 库，
//      与 DSH 版本升级天然隔离，不依赖任何官方未发布组件。
//   2. 各服务商钥匙分开保存，只从本机配置或对应环境变量读取，绝不打印、不进日志、不进错误信息；
//      RPC 返回钥匙只脱敏回显（前 4 后 4）。
//   3. 只调用各服务商官方 REST API，不引入 SDK 或 DSH 内部运行时依赖。
import { existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { parse, stringify } from 'yaml'

const EXA_DEFAULT_NUM_RESULTS = 5
const MAX_NUM_RESULTS = 20
const EXA_SNIPPET_MAX_CHARS = 500
const ROUTE_PREFIX = '/_dsh/dsh-song-search'
const PATCH_ROW_ID = 'dsh-song-search'
const PROVIDER_DEFINITIONS = {
  exa: { label: 'Exa', envKey: 'EXA_API_KEY', baseURL: 'https://api.exa.ai', path: '/search', method: 'POST' },
  brave: { label: 'Brave Search', envKey: 'BRAVE_SEARCH_API_KEY', baseURL: 'https://api.search.brave.com/res/v1', path: '/web/search', method: 'GET' },
  tavily: { label: 'Tavily', envKey: 'TAVILY_API_KEY', baseURL: 'https://api.tavily.com', path: '/search', method: 'POST' },
  serper: { label: 'Serper（Google）', envKey: 'SERPER_API_KEY', baseURL: 'https://google.serper.dev', path: '/search', method: 'POST' },
}
const THIRD_PARTY_PROVIDER_IDS = Object.keys(PROVIDER_DEFINITIONS)
const PROVIDER_LABELS = { ...Object.fromEntries(THIRD_PARTY_PROVIDER_IDS.map((id) => [id, PROVIDER_DEFINITIONS[id].label])), 'deepseek-official': 'DeepSeek' }

function isThirdPartyProvider(provider) {
  return THIRD_PARTY_PROVIDER_IDS.includes(provider)
}

function maxResultsFor(request) {
  const value = request && request.maxResults
  if (!Number.isInteger(value) || value <= 0) return EXA_DEFAULT_NUM_RESULTS
  return Math.min(value, MAX_NUM_RESULTS)
}

function storedApiKey(config, provider = 'exa') {
  if (!config || typeof config !== 'object') return null
  if (provider === 'exa' && typeof config.apiKey === 'string' && config.apiKey.length > 0) return config.apiKey
  const apiKeys = config.apiKeys
  if (apiKeys && typeof apiKeys === 'object' && typeof apiKeys[provider] === 'string' && apiKeys[provider].length > 0) return apiKeys[provider]
  return null
}

// 纯函数：从 config 或对应环境变量解析钥匙（不打印、不记录、不落盘）
export function resolveApiKey(config, provider = 'exa') {
  const configured = storedApiKey(config, provider)
  if (configured) return configured
  const envKey = PROVIDER_DEFINITIONS[provider] && PROVIDER_DEFINITIONS[provider].envKey
  if (envKey && typeof process !== 'undefined' && process.env && typeof process.env[envKey] === 'string' && process.env[envKey].length > 0) return process.env[envKey]
  return null
}

function mapResultList(results, getUrl, getTitle, getSnippet) {
  const list = Array.isArray(results) ? results : []
  const sources = list
    .map((r) => ({ row: r, url: getUrl(r), title: getTitle(r), snippet: getSnippet(r) }))
    .filter((item) => item.row && typeof item.url === 'string' && item.url.length > 0)
    .map((r) => ({
      url: r.url,
      ...(typeof r.title === 'string' && r.title.length > 0 ? { title: r.title } : {}),
      ...(typeof r.snippet === 'string' && r.snippet.length > 0 ? { snippet: r.snippet.slice(0, EXA_SNIPPET_MAX_CHARS) } : {}),
    }))
  return { sources, truncated: false }
}

// 纯函数：把各服务商响应映射为 DSH 的 WebSearchResult 形状
export function mapExaResults(data) {
  return mapResultList(data && data.results, (r) => r && r.url, (r) => r && r.title, (r) => r && r.text)
}

export function mapBraveResults(data) {
  return mapResultList(data && data.web && data.web.results, (r) => r && r.url, (r) => r && r.title, (r) => {
    if (!r) return ''
    return [r.description, ...(Array.isArray(r.extra_snippets) ? r.extra_snippets : [])].filter((x) => typeof x === 'string' && x.length > 0).join(' ')
  })
}

export function mapTavilyResults(data) {
  return mapResultList(data && data.results, (r) => r && r.url, (r) => r && r.title, (r) => r && r.content)
}

export function mapSerperResults(data) {
  return mapResultList(data && data.organic, (r) => r && r.link, (r) => r && r.title, (r) => r && r.snippet)
}

function mapProviderResults(provider, data) {
  if (provider === 'brave') return mapBraveResults(data)
  if (provider === 'tavily') return mapTavilyResults(data)
  if (provider === 'serper') return mapSerperResults(data)
  return mapExaResults(data)
}

function requestHeaders(provider, apiKey) {
  if (provider === 'brave') return { 'x-subscription-token': apiKey }
  if (provider === 'tavily') return { authorization: 'Bearer ' + apiKey }
  if (provider === 'serper') return { 'x-api-key': apiKey }
  return { authorization: 'Bearer ' + apiKey, 'x-api-key': apiKey }
}

function requestBody(provider, query, numResults, options) {
  if (provider === 'tavily') return { query, max_results: numResults, search_depth: 'basic', include_answer: false }
  if (provider === 'serper') return { q: query, num: numResults }
  return {
    query,
    numResults,
    type: options.searchType || 'auto',
    ...(options.highlights ? { contents: { highlights: true } } : {}),
  }
}

function buildProviderUrl(provider, options, query, numResults) {
  const endpoint = options.baseURL + PROVIDER_DEFINITIONS[provider].path
  if (provider !== 'brave') return endpoint
  const params = new URLSearchParams({ q: query, count: String(numResults), extra_snippets: 'true' })
  return endpoint + '?' + params.toString()
}

// 组装搜索提供商（provider 契约与 DSH ctx.web 接缝一致：id / available / search）
export function buildSearchProvider(provider, resolveOptions) {
  const definition = PROVIDER_DEFINITIONS[provider]
  if (!definition) throw new Error('Unknown search provider: ' + provider)
  return {
    id: provider,
    available() {
      const options = resolveOptions()
      return Boolean(options.apiKey) && URL.canParse(options.baseURL)
    },
    async search(request, signal) {
      const options = resolveOptions()
      const query = String((request && request.query) || '')
      const numResults = maxResultsFor(request)
      const endpoint = buildProviderUrl(provider, options, query, numResults)
      const headers = { 'content-type': 'application/json', 'accept': 'application/json', ...requestHeaders(provider, options.apiKey), 'user-agent': 'dsh-song-search/0.3.0' }
      let response
      try {
        response = await fetch(endpoint, {
          method: definition.method,
          redirect: 'error',
          headers,
          ...(definition.method === 'GET' ? {} : { body: JSON.stringify(requestBody(provider, query, numResults, options)) }),
          ...(signal !== undefined ? { signal } : {}),
        })
      } catch (err) {
        throw new Error(definition.label + ' search request failed: ' + String((err && err.message) || err))
      }
      if (!response.ok) {
        throw new Error(definition.label + ' API error (HTTP ' + response.status + ')')
      }
      let data
      try {
        data = await response.json()
      } catch (err) {
        throw new Error(definition.label + ' returned an unprocessable response body')
      }
      return mapProviderResults(provider, data)
    },
  }
}

export function buildExaSearchProvider(resolveOptions) { return buildSearchProvider('exa', resolveOptions) }
export function buildBraveSearchProvider(resolveOptions) { return buildSearchProvider('brave', resolveOptions) }
export function buildTavilySearchProvider(resolveOptions) { return buildSearchProvider('tavily', resolveOptions) }
export function buildSerperSearchProvider(resolveOptions) { return buildSearchProvider('serper', resolveOptions) }

// 定位 profile patch 文件：config.patchFilePath 优先，否则自动探测
// （遍历 $DSH_HOME/profiles/*/cordis.patch.yml，找包含本插件行 id 的文件）
export function locatePatchFile(config) {
  if (config && typeof config.patchFilePath === 'string' && config.patchFilePath.length > 0) return config.patchFilePath
  const home = typeof process.env.DSH_HOME === 'string' && process.env.DSH_HOME.length > 0 ? process.env.DSH_HOME : join(homedir(), '.dsh')
  const profilesDir = join(home, 'profiles')
  if (!existsSync(profilesDir)) return null
  try {
    for (const entry of readdirSync(profilesDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const patch = join(profilesDir, entry.name, 'cordis.patch.yml')
      if (existsSync(patch) && readFileSync(patch, 'utf8').includes(PATCH_ROW_ID)) return patch
    }
  } catch (err) { /* 探测失败则返回 null，由调用方报错 */ }
  return null
}

// 读取当前搜索配置（钥匙只脱敏回显，绝不返回完整钥匙）
export function readSearchConfig(patchPath) {
  if (!patchPath || !existsSync(patchPath)) return { ok: false, error: '找不到 profile 配置文件（cordis.patch.yml）' }
  let doc
  try {
    doc = parse(readFileSync(patchPath, 'utf8'))
  } catch (err) {
    return { ok: false, error: '配置文件解析失败，请检查格式或联系维护者' }
  }
  const rows = Array.isArray(doc) ? doc : []
  const webRow = rows.find((r) => r && r.id === 'web')
  const providerRow = rows.find((r) => r && r.id === PATCH_ROW_ID)
  const provider = webRow && webRow.config && typeof webRow.config.searchProvider === 'string' ? webRow.config.searchProvider : null
  const providerId = isThirdPartyProvider(provider) ? provider : null
  const apiKey = providerId ? (storedApiKey(providerRow && providerRow.config, providerId) || '') : ''
  const masked = apiKey.length > 4 ? apiKey.slice(0, 4) + '****' + apiKey.slice(-4) : apiKey.length > 0 ? '****' : ''
  const exaKey = storedApiKey(providerRow && providerRow.config, 'exa') || ''
  const exaMasked = exaKey.length > 4 ? exaKey.slice(0, 4) + '****' + exaKey.slice(-4) : exaKey.length > 0 ? '****' : ''
  return {
    ok: true,
    provider: provider || 'deepseek-official',
    providerLabel: PROVIDER_LABELS[provider] || provider || 'DeepSeek',
    apiKeySet: apiKey.length > 0,
    apiKeyMasked: masked,
    // 保留旧字段，便于已安装的旧 client bundle 平滑升级。
    exaKeySet: exaKey.length > 0,
    exaKeyMasked: exaMasked,
    patchFile: patchPath,
  }
}

// 修改搜索配置：provider（第三方 provider / deepseek-official）+ 可选 apiKey
export function writeSearchConfig(patchPath, next) {
  if (!patchPath) return { ok: false, error: '找不到 profile 配置文件（cordis.patch.yml）' }
  const requestedProvider = next && typeof next.provider === 'string' ? next.provider : ''
  const provider = isThirdPartyProvider(requestedProvider) || requestedProvider === 'deepseek-official' ? requestedProvider : 'deepseek-official'
  let doc
  try {
    doc = parse(readFileSync(patchPath, 'utf8'))
  } catch (err) {
    return { ok: false, error: '配置文件解析失败，无法保存' }
  }
  if (!Array.isArray(doc)) return { ok: false, error: '配置文件结构异常，无法保存' }
  let webRow = doc.find((r) => r && r.id === 'web')
  if (!webRow) { webRow = { id: 'web' }; doc.push(webRow); }
  if (!webRow.config || typeof webRow.config !== 'object') webRow.config = {}
  webRow.config.searchProvider = provider
  if (isThirdPartyProvider(provider) && next && typeof next.apiKey === 'string' && next.apiKey.length > 0) {
    let providerRow = doc.find((r) => r && r.id === PATCH_ROW_ID)
    if (!providerRow) { providerRow = { id: PATCH_ROW_ID }; doc.push(providerRow); }
    if (!providerRow.config || typeof providerRow.config !== 'object') providerRow.config = {}
    if (!providerRow.config.apiKeys || typeof providerRow.config.apiKeys !== 'object' || Array.isArray(providerRow.config.apiKeys)) providerRow.config.apiKeys = {}
    providerRow.config.apiKeys[provider] = next.apiKey
    // 保留旧版本 Exa 配置格式，支持从旧 bundle 升级后继续使用原钥匙。
    if (provider === 'exa') providerRow.config.apiKey = next.apiKey
  }
  try {
    writeFileSync(patchPath, stringify(doc) + '\n')
  } catch (err) {
    return { ok: false, error: '配置文件写入失败，请检查文件权限' }
  }
  return { ok: true, provider: provider }
}

// 同源防护：有副作用的 RPC 只允许 POST + 严格同源
function sameOrigin(req) {
  const fetchSite = (req.headers && (req.headers['sec-fetch-site'] || '')) || ''
  const origin = (req.headers && req.headers.origin) || ''
  const host = (req.headers && req.headers.host) || ''
  if (origin) return host.length > 0 && (origin === 'http://' + host || origin === 'https://' + host)
  return fetchSite === 'same-origin' || fetchSite === 'none'
}

function readBody(req, maxBytes) {
  return new Promise(function (resolve, reject) {
    let size = 0
    const chunks = []
    req.on('data', function (c) { size += c.length; if (size > maxBytes) { reject(Object.assign(new Error('payload too large'), { status: 413 })); req.destroy(); return; } chunks.push(c); })
    req.on('end', function () { resolve(Buffer.concat(chunks).toString('utf8')); })
    req.on('error', reject)
  })
}

function respond(res, status, payload) {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(JSON.stringify(payload))
}

// 注册进 ctx.web + 挂载 RPC 路由
function apply(ctx, config) {
  for (const provider of THIRD_PARTY_PROVIDER_IDS) {
    const definition = PROVIDER_DEFINITIONS[provider]
    ctx.web.registerSearchProvider(buildSearchProvider(provider, () => ({
      apiKey: resolveApiKey(config, provider),
      // Exa 的 baseURL 覆盖是旧配置能力；新服务只使用各自官方端点。
      baseURL: provider === 'exa' && config && typeof config.baseURL === 'string' && config.baseURL.length > 0 ? config.baseURL : definition.baseURL,
      searchType: config && config.searchType,
      highlights: Boolean(config && config.highlights),
    })))
  }

  ctx.inject(['webServer'], function (webCtx) {
    webCtx.effect(function () {
      try {
        const dispose = webCtx.webServer.register({
          kind: 'prefix',
          path: ROUTE_PREFIX,
          handler: async function (req, res) {
            try {
              const url = new URL(req.url || '/', 'http://localhost')
              const method = decodeURIComponent(url.pathname.slice(ROUTE_PREFIX.length + 1))
              if (method === 'getSearchConfig' && (req.method === 'GET' || req.method === 'POST')) {
                respond(res, 200, readSearchConfig(locatePatchFile(config)))
                return
              }
              if (method === 'setSearchConfig') {
                if (req.method !== 'POST') { respond(res, 405, { error: 'setSearchConfig requires POST' }); return; }
                if (!sameOrigin(req)) { respond(res, 403, { error: 'cross-origin request rejected' }); return; }
                const raw = await readBody(req, 64 * 1024)
                let args = {}
                if (raw.length > 0) { try { args = JSON.parse(raw); } catch (e) { respond(res, 400, { error: 'invalid JSON body' }); return; } }
                respond(res, 200, writeSearchConfig(locatePatchFile(config), args))
                return
              }
              respond(res, 404, { error: 'unknown method: ' + method })
            } catch (err) {
              respond(res, 500, { error: 'internal error' })
            }
          },
        })
        return function () { dispose(); }
      } catch (err) {
        console.warn('[dsh-song-search] webServer 路由注册失败', String((err && err.message) || err))
      }
    }, 'dsh-song-search: RPC routes')
  }, 'dsh-song-search: RPC routes')
}

export default { name: 'dsh-song-search', inject: ['web'], apply }
